baseurl = "https://caiovictormc.github.io/" # Hostname (and path) to the root.
title = "Caio Victor" # Site title.
theme = "hugo-coder"
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "disqus_rXfHxWJzsM" # Enable or disable Disqus.

[params] # theme parameters
    author = "Caio Victor" # Author's name.
    info = "Software Developer" # Author's job title or info.
    description = "Caio Victor's personal blog" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "okabe.jpeg" # Contain the path of the optionnal avatar in the static folder.

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/caiovictormc/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/caiovictormc/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/caiovictormc/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"
